resources:
- name: peters-pipelines
  type: git
  source:
    uri: https://github.com/mgunter-pivotal/peters-pipelines.git 
    private_key: {{github_private_key}}
jobs:
- name: initialize-helm
  plan:
  - get: peters-pipelines
  - task: authenticate-kubernetes
    file: peters-pipelines/kubernetes/tasks/authenticate-kubernetes/task.yml
    params:
      PKS_API_URL: {{pks_api_url}}
      PKS_API_USERNAME: {{pks_api_username}}
      PKS_API_PASSWORD: {{pks_api_password}}
      PKS_CLUSTER_NAME: {{pks_cluster_name}}
  - task: setup-tiller
    file: peters-pipelines/kubernetes/tasks/setup-tiller/task.yml
