---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

inputs:
  - name: peters-pipelines
  - name: chart-repo
  - name: kube-config

run:
  path: peters-pipelines/kubernetes/tasks/deploy-chart/task.sh